require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comedians", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Comedian. As you add validations to Comedian, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Comedian.create! valid_attributes
      get comedians_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      comedian = Comedian.create! valid_attributes
      get comedian_url(comedian)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_comedian_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      comedian = Comedian.create! valid_attributes
      get edit_comedian_url(comedian)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Comedian" do
        expect {
          post comedians_url, params: { comedian: valid_attributes }
        }.to change(Comedian, :count).by(1)
      end

      it "redirects to the created comedian" do
        post comedians_url, params: { comedian: valid_attributes }
        expect(response).to redirect_to(comedian_url(Comedian.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comedian" do
        expect {
          post comedians_url, params: { comedian: invalid_attributes }
        }.to change(Comedian, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post comedians_url, params: { comedian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comedian" do
        comedian = Comedian.create! valid_attributes
        patch comedian_url(comedian), params: { comedian: new_attributes }
        comedian.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the comedian" do
        comedian = Comedian.create! valid_attributes
        patch comedian_url(comedian), params: { comedian: new_attributes }
        comedian.reload
        expect(response).to redirect_to(comedian_url(comedian))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        comedian = Comedian.create! valid_attributes
        patch comedian_url(comedian), params: { comedian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comedian" do
      comedian = Comedian.create! valid_attributes
      expect {
        delete comedian_url(comedian)
      }.to change(Comedian, :count).by(-1)
    end

    it "redirects to the comedians list" do
      comedian = Comedian.create! valid_attributes
      delete comedian_url(comedian)
      expect(response).to redirect_to(comedians_url)
    end
  end
end
