require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pevents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Pevent. As you add validations to Pevent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pevent.create! valid_attributes
      get pevents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pevent = Pevent.create! valid_attributes
      get pevent_url(pevent)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pevent_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pevent = Pevent.create! valid_attributes
      get edit_pevent_url(pevent)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pevent" do
        expect {
          post pevents_url, params: { pevent: valid_attributes }
        }.to change(Pevent, :count).by(1)
      end

      it "redirects to the created pevent" do
        post pevents_url, params: { pevent: valid_attributes }
        expect(response).to redirect_to(pevent_url(Pevent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pevent" do
        expect {
          post pevents_url, params: { pevent: invalid_attributes }
        }.to change(Pevent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pevents_url, params: { pevent: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pevent" do
        pevent = Pevent.create! valid_attributes
        patch pevent_url(pevent), params: { pevent: new_attributes }
        pevent.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pevent" do
        pevent = Pevent.create! valid_attributes
        patch pevent_url(pevent), params: { pevent: new_attributes }
        pevent.reload
        expect(response).to redirect_to(pevent_url(pevent))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pevent = Pevent.create! valid_attributes
        patch pevent_url(pevent), params: { pevent: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pevent" do
      pevent = Pevent.create! valid_attributes
      expect {
        delete pevent_url(pevent)
      }.to change(Pevent, :count).by(-1)
    end

    it "redirects to the pevents list" do
      pevent = Pevent.create! valid_attributes
      delete pevent_url(pevent)
      expect(response).to redirect_to(pevents_url)
    end
  end
end
